### ISSUE TITLE
The Number of Datasets in the Link is Inconsistent with the Paper

### ISSUE THREAD

**Issue by buyi6666** [wyf0912/flare-removal#3]
Hi！ ⭐⭐⭐
The dataset you have collected is very rich, including many scenes and multiple light sources！👍👍👍

In the paper, you capture 1251 sets of images. 281 sets among them are used for the evaluation, and 970 sets are used for training purposes.

But I downloaded 868 pairs of training images and 40 pairs of test images.

Is there any omission?

Thank you for your work again!!! ❀❀❀

**Comment by wyf0912** [comment]
Thanks for your interest in our work...

It seems that I omitted some data when I prepared the release of the dataset. I will update the dataset recently.

**Comment by wyf0912** [comment]
Hi,
I update the link to the corrected dataset

https://drive.google.com/file/d/1fA9mlExcgiNxUD_kpvycVMN6s8p5FEmW/view?usp=sharing

**Comment by buyi6666** [comment]
Thank you very much!!!♥
